module.exports = [
  {
    id: 136,
    item_name: "Direct Deposit",
    amount: 5000,
    date: "2023-10-14",
    transaction_from: "Employer",
    category: "Income",
  },
  {
    id: 137,
    item_name: "Groceries",
    amount: 300,
    transaction_from: "Shop Rite",
    date: "2023-10-15",
    category: "Food",
  },
  {
    id: 138,
    item_name: "Savings",
    amount: 1000,
    transaction_from: "Chase Bank",
    date: "2023-10-16",
    category: "Savings",
  },
  {
    id: 139,
    item_name: "Utilities",
    amount: 150,
    transaction_from: "Con Ed",
    date: "2023-10-15",
    category: "Expenses",
  },
{
    id: 140,
    item_name: "Pet Food",
    amount: 30,
    transaction_from: "Pet Store",
    date: "2023-10-15",
    category: "Pets",
  },
{
    id: 141,
    item_name: "Rent",
    amount: 1500,
    transaction_from: "Landlord",
    date: "2023-10-14",
    category: "Housing",
  },
]